name: Cypress Allure Report

on: [push]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests and generate Allure report
              run: |
                  npm run cy:tests-with-allure-headless

            - name: Generate Allure report
              run: |
                  npm install -g allure-commandline
                  mkdir -p allure-results
                  cp -r ./test-results/* ./allure-results/
                  allure generate allure-results --clean -o allure-report
              continue-on-error: true # Allow the workflow to continue even if Allure report generation fails

            - name: Upload Allure report artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: allure-report
                  path: ./allure-report

    deploy:
        needs: build # Ensure that the 'build' job is completed successfully
        runs-on: windows-latest

        steps:
            - name: Checkout target repository
              uses: actions/checkout@v2
              with:
                  repository: Karpovich0/cypress-cucumber-telnyx # Replace with the target repository's owner and name
                  ref: allure-report # Replace with the branch where you want to push the report

            - name: Download Allure report artifact
              uses: actions/download-artifact@v2
              with:
                  name: allure-report
                  path:

            - name: Commit and push Allure report
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "<actions@github.com>"
                  git add .
                  git commit -m "Add Allure report"
                  git push
